import "../css/main.css";
import "./LazyLoadImages";
import "./colorPallete";
import "./sidebar";
import "./countDownDate";
import "./aos-scroll";
// import "./locomotive-scroll";
// import "./userDetails";
// import "./tinySlider";
import "./backToTop";
import "./pkfan-modal";
